Ada.Service/KeoghsClientSite/Models/BatchListViewModel.cs
using MDA.WCF.WebServices.Messages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KeoghsClientSite.Models
{
    public class BatchListViewModel
    {
        public BatchListViewModel()
        {
            // 
            PagingInfo=new PagingInfo();
        }
        
        public List<ExWebsiteBatchDetails> BatchList { get; set; }
        //
        public string SortColumn { get; set; }

        // Specifies if the sort order for the results list is in 
        // ascending or descending order
        public bool SortAscending { get; set; }

        public IEnumerable<SelectListItem> Clients { get; set; }
        //
        public int? SelectedClientId { get; set; }
        //
        public int SelectedTeamId { get; set; }
        //
        public int SelectedUserId { get; set; }
        //
        public PagingInfo PagingInfo { get; set; }
        //
        public string ExpectedFileExtension { get; set; }
    }
}

Ada.Service/KeoghsClientSite/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KeoghsClientSite.Models;
using KeoghsClientSite.Models.SingleClaim;
using KeoghsClientSite.Repositories;
using KeoghsClientSite.ActionFilters;
using KeoghsClientSite.StaticClasses;
using MDA.WCF.WebServices.Messages;
using KeoghsClientSite.FileUpload;
using MDA.Common;
using Newtonsoft.Json;
using KeoghsClientSite.Repositories.SingleClaimRepository; 

namespace KeoghsClientSite.Controllers
{
    [NoCache]
    [RedirectingAction]
    public class UploadController : Controller
    {
        //
        [NoCache]
        [Authorize]
        public ActionResult Index(BatchListViewModel batchListViewModel)
        {
            int totalOutstanding = 0;
      
            if (Request.HttpMethod == "GET")
            {
                BatchListViewModel newBatchListViewModel = new BatchListViewModel();
                batchListViewModel = Repository.PopulateBatchListViewModel(false, newBatchListViewModel);
                
            }
            else
            {
                batchListViewModel = Repository.PopulateBatchListViewModel(true, batchListViewModel);
            }

            totalOutstanding = SingleClaimRepository.GetTotalSingleClaimsForClient();

            ViewData["OutstandingClaimsCount"] = totalOutstanding;

            return View(batchListViewModel);
        }
        //
        [AjaxAuthorize]
        public JsonResult IsClientBatchReferenceUnique(string clientBatchReference)
        {
            //
            return Json(Repository.IsClientBatchReferenceUnique(clientBatchReference)); ;
            //
        }
        //
        [AjaxAuthorize]
        public JsonResult GetBatchProcessingResults(int batchId)
        {
            BatchProcessingResultsAjaxResponse batchProcessingResultsAjaxResponse = new BatchProcessingResultsAjaxResponse();
            GetBatchProcessingResultsResponse batchProcessingResultsResponse;

            batchProcessingResultsResponse = Repository.GetBatchProcessingResults(batchId);

            //
            if (batchProcessingResultsResponse.Error == null)
            {
                //
                List<DynaTreeNode> NodesArray = new List<DynaTreeNode>();

                Repository.CreateTreeNode(NodesArray, null, batchProcessingResultsResponse.ProcessingResults);

                string jsonstring = JsonConvert.SerializeObject(NodesArray.ToArray());

                batchProcessingResultsAjaxResponse.Result = jsonstring;

            }
            else
            {
                batchProcessingResultsAjaxResponse.Error = batchProcessingResultsResponse.Error;
            }

            return Json(batchProcessingResultsAjaxResponse);
        }
    }
}

Ada.Service/KeoghsClientSite/Views/Upload/Index.cshtml
@using System.Web.Configuration;
@using System.Configuration;
@model KeoghsClientSite.Models.BatchListViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutNew.cshtml";
}
@section scripts{
    
      @Scripts.Render("~/bundles/jqueryfileupload")

     @Scripts.Render("~/bundles/jscustomupload")

    
  
    <script src="~/Scripts/jquery.corner.js"></script>

    <script src="~/Scripts/jquery.cookie.js" type="text/javascript"></script> 
    
    <link href="~/Content/themes/dynaTree/ui.dynatree.css" rel="stylesheet" type="text/css" id="skinSheet"> 
    
    <script src="~/Scripts/jquery.dynatree.js" type="text/javascript"></script>


    <script language="javascript">
        $('#ClearButton').corner("5px");
        $('#FileSubmit').corner("5px");
        $('#Browse').corner("5px");
        $(document).ready(function () {
            var uploadFileSectionVisible = $('#UploadFileSectionVisible').val();
            var uploadFileSectionReadOnly = $('#UploadFileSectionReadOnly').val();
            var batchReportsSectionVisible = $('#BatchReportsSectionVisible').val();
            var batchReportsSectionReadOnly = $('#BatchReportsSectionReadOnly').val();
            var singleClaimsVisible = $('#SingleClaimsVisible').val();

            if (singleClaimsVisible != 'true') {
                $('#SingleClaimHeader').css('opacity', '0.5');
                $('#singleClaimAnchor').css('cursor', 'default');
                $('#singleClaimAnchor').click(function (e) {
                    e.preventDefault();
                });

                $('#OutstandingClaimsHeader').css('opacity', '0.5');
                $('#outstandingClaimsAnchor').css('cursor', 'default');
                $('#outstandingClaimsAnchor').click(function (e) {
                    e.preventDefault();
                });
            }
            
            if (uploadFileSectionVisible != 'true' && batchReportsSectionVisible != 'true') {
                $('#UploadHeader').css('opacity', '0.5');
                $('#uploadAnchor').css('cursor', 'default');
                $('#uploadAnchor').click(function (e) {
                        e.preventDefault();
                });
            }

            if (batchReportsSectionVisible != 'true') {
                $('#BatchLevelReports').css('visibility', 'hidden');
            }

            if (batchReportsSectionReadOnly == 'true') {
                //$('#BatchLevelReports :input').attr('disabled', true);
                //$('.action-arrow').mouseover(function () {
                //    $('[id^=actions').css('cursor', 'default');
                //});
            }

            if (uploadFileSectionVisible != 'true') {
                $('#divFileUpload').css('visibility', 'hidden');
                $('#divUploadProgress').css('visibility', 'hidden');
            }

            if (uploadFileSectionReadOnly == 'true') {
                $('#divUploadProgress').css('visibility', 'hidden');
            }

            if (uploadFileSectionReadOnly == 'true') {
                $('#divFileUpload').css('opacity', '0.5');
                $('#divFileUpload').css('filter', 'alpha(opacity = 50)');
                $('#divFileUpload :input').attr('disabled', true);
                $('#btnBrowse').css('opacity', '0.5');
                $('#btnBrowse').css('filter', 'alpha(opacity = 50)');
                $('#btnBrowse').css('cursor', 'default');
                $('#fileupload').css('cursor', 'default');
                $('#ClearButton').css('opacity', '0.5');
                $('#ClearButton').css('filter', 'alpha(opacity = 50)');
                $('#ClearButton').css('cursor', 'default');
                $('#FileSubmit').css('opacity', '0.5');
                $('#FileSubmit').css('filter', 'alpha(opacity = 50)');
                $('#FileSubmit').css('cursor', 'default');
             
              
            }
            

        });
    </script>

    

}

 @{
     if (System.Configuration.ConfigurationManager.AppSettings["ShowSingleClaim"] == "true")
     {
        Html.RenderPartial("_UploadMenuSingleClaim");
     }
     else
     {
         Html.RenderPartial("_UploadMenu");
     }
  }

@foreach (var item in SiteHelpers.LoggedInUser.TemplateFunctions)
{
    switch(item.Key){
        case "chkEnabled_2_BatchUpload":
            <input type="hidden" id="UploadFileSectionVisible" value='true' />
            break;
            case "chkReadOnly_2_BatchUpload":
            <input type="hidden" id="UploadFileSectionReadOnly" value='true' />
            break;
            case "chkEnabled_3_BatchLevelReports":
            <input type="hidden" id="BatchReportsSectionVisible" value='true' />
            break;
            case "chkReadOnly_3_BatchLevelReports":
            <input type="hidden" id="BatchReportsSectionReadOnly" value='true' />
            break;
            case "chkEnabled_4_SingleClaimInput":
            <input type="hidden" id="SingleClaimsVisible" value='true' />
            break;
            

    }
}


   

  <div class="content_wrapper"> 
    <!--content_wrapper  div starts here-->
        <div class="row" > 
            <!--row div starts here-->
            <div class="span6 border-radius white_bg paddingbottom_30 webpart" id="divFileUpload">
                <!--span5 div starts here-->
                <!--new_claim_container div starts here-->
                <div class="headings border_bottom left blue_bg">
                    <div class="col-1 w388 paddingtop_12 paddingbottom_10 paddingleft_10">
                        <h1> UPLOAD BATCH DATA FILE</h1>
                    </div>
                </div>

                <form action="/FileUpload/UploadHandler.ashx" method="POST" enctype="multipart/form-data" id="uploadForm">

                    <div class="upload_batch_container row">

                        <div class="forms left">
                            <div class="col-1 w386 ">
                                <h1> Upload ADA File<br></h1>
                            </div>
                            <div class="col-2 w386">
                                <input type="text" name="filetext" id="filetext" class="fileupload" readonly />
                                
                                <span class="btn btn-success fileinput-button NFFileButton" id="btnBrowse">
                                    <input id="fileupload" type="file" name="files[]" data-url="/FileUpload/UploadHandler.ashx" />
                                </span>
                            </div>

                            <div class="col-1">
                                <br>
                                <h1>Batch Reference</h1>
                            </div>

                            <div class="col-2">
                                <input id="batchref" name="batchref" type="text" class="upload_batch_input" maxlength="50" title="Maximum of 50 characters">
                            </div>
                        </div>

                        <div class="button right">
                            <button id="ClearButton" type="button" class="btn btn-primary start styled-button-clear">
                                <span>Reset</span>
                            </button>

                            <button id="FileSubmit" type="button" class="btn btn-primary start styled-button-submit">
                                <span>Submit</span>
                            </button>


                        </div>

                    </div>
                </form>

                <!--upload_batch_container div ends here-->

            </div>
            <!--span6 div ends here-->
          
            <div style="height:225px;" class="span12 border-radius white_bg  webpart" id="divUploadProgress">

                    <div id="UploadHeader" class="aligncenter paddingtop_12 paddingbottom_10"> <h2>  </h2>
                        @*<p>&nbsp;</p>*@
                    </div>
       
                    <div id="UploadIcon" class="aligncenter paddingtop_12 paddingbottom_15">
                    
                        <i> </i>
                         
                        <img src="~/Images/loading.png" id="rotate" style="display:none;">

                    </div>
       
                    <div id="UploadFooter" class="aligncenter paddingbottom_15 blue" style="margin-top:-5px;">
                    
                        <table style="text-align:center;margin:auto;">

                            <tr>
                                <td>
                                     <h2 id="FooterText">  </h2>  
                                   
                                </td>
                                 <td id="ButtonCell" style="vertical-align:top;">
                                      &nbsp;<input type="button" class="styled-button" value="Continue" id="ContinueButton" style="display:none;margin-top:-2px;" />
                                     
                                         <input type="button" class="styled-button" value="Show Error" id="ShowErrorButton" style="display:none;margin-top:-2px;" />
                                    
                                </td>
                            </tr>
                        </table>
                    </div>
            </div>


        </div> <!--row div ends here-->
    
        @using (Html.BeginForm("Index", "Upload", FormMethod.Post, new { id = "BatchForm" }))
        {
       
            Html.RenderPartial("_BatchList",Model);
          
            @Html.HiddenFor(model => model.ExpectedFileExtension)
        }

      @{    
            int maxRequestLength=0;
            HttpRuntimeSection section =
            ConfigurationManager.GetSection("system.web/httpRuntime") as HttpRuntimeSection;
            if (section != null) 
            { maxRequestLength = section.MaxRequestLength;        }
          
      }

     
      @Html.Hidden("FileUploadMaxSize", maxRequestLength)

    <!--content_wrapper  div ends here--> 
    </div>

<div id="BatchError" style="display:none;"><h2></h2>

      <button id="BatchErrorDialogOK" type="button" class="btn btn-primary start styled-button">
                                <span>OK</span>
                            </button>
</div>

Ada.Service/KeoghsClientSite/Views/Upload/_BatchList.cshtml
@model KeoghsClientSite.Models.BatchListViewModel
@using KeoghsClientSite.StaticClasses
@using MDA.WCF.WebServices.Messages;


<div class="row" id="BatchLevelReports">
    <!--row div starts here-->

    <div class="span18 white_bg webpart border-radius">
        <!--span18 div starts here-->
        <div class="result_container row">
            <div class="headings blue_bg w1214 border_bottom left">
                <!--heading div starts here-->
                <div class="col-1 w1024">
                    <h1>BATCH LEVEL REPORTS</h1>
                </div>
                @*<div style="float:right;padding-right:20px;padding-top:5px;">
                    @{bool IsAdminEnabled = false;}
                    @foreach (var item in SiteHelpers.LoggedInUser.TemplateFunctions)
                    {
                        if (item.Key == "chkEnabled_25_ADAMAINTENANCE") { 
                                IsAdminEnabled = true;
                                break;
                        }
                    }

                    @if (IsAdminEnabled)
                    {
                        @Html.DropDownListFor(model => model.SelectedClientId, new SelectList(Model.Clients, "Value", "Text"),
                            "--- All Clients ---", new { @class = "FilterDropdowns" })
                    }

                  

                </div>*@
                @Html.HiddenFor(model => model.PagingInfo.ItemsPerPage)
                @Html.HiddenFor(model => model.SortColumn)
                @Html.HiddenFor(model => model.SortAscending)
                @Html.HiddenFor(model => model.PagingInfo.CurrentPage)
                @Html.HiddenFor(model => model.PagingInfo.TotalPages)
                @Html.HiddenFor(model => model.PagingInfo.TotalItems)
            </div>
            <!--heading div ends here-->
            <div class="result_container headers">

                <div class="row-1 left">
                    <!--row div starts here-->
                    <div class="col-1 w232">
                        <h4><a href="javascript:void(0)" class="SortCol" id="CLIENTBATCHREFERENCE" title="Client Batch Reference">Batch Reference <i class="icon-small up-arrow"></i></a> </h4>
                    </div>
                    <div class="col-2 w232">
                        <h4><a href="javascript:void(0)" class="SortCol" id="TOTALNUMBEROFCLAIMS" title="Total Number of Claims"> Total Number of Claims <i class="icon-small up-arrow"></i> </a> </h4>
                    </div>
                    <div class="col-2 w232">
                        <h4> <a href="javascript:void(0)" class="SortCol" id="UPLOADEDBY" title="Uploaded By"> Uploaded By <i class="icon-small up-arrow"></i>  </a>  </h4>
                    </div>
                    @* <div class="col-3 w232">*@

                    <div class="col-3 w183">

                        <h4>  <a href="javascript:void(0)" class="SortCol" id="UPLOADDATETIME" title="Upload Date/Time"> Upload Date/Time <i class="icon-small up-arrow"></i>   </a>  </h4>
                    </div>
                    @*<div class="col-3 w232">*@
                    <div class="col-3">
                        <h4>  <a href="javascript:void(0)" class="SortCol" id="STATUS" title="Batch Status"> Batch Status <i class="icon-small up-arrow"></i>   </a>  </h4>
                    </div>
                    @* <div class="col-7 w232">*@

                    <div class="col-7">
                        <h4> <i class="icon-small up-arrow" style="visibility:hidden;"></i> Actions</h4>
                    </div>
                </div>
                <!--row div ends here-->
                <!-- Dropdown div starts here-->
                <!-- Dropdown div Ends here-->
                @{

                    int RowNum = 0;
                    int MarginTop = 96;
                }
                @foreach (ExWebsiteBatchDetails batch in Model.BatchList)
                {
                    RowNum += 1;
                    <div class="row-2 border_bottom_solid-1 red left">
                        <!--row-2 div starts here-->
                        @*<div class="col-1 w232 paddingleft_24 *@

                        <div class="col-1 w232">
                            <h4 title="@batch.ClientBatchReference">@(batch.ClientBatchReference.Length <= 16 ? batch.ClientBatchReference : batch.ClientBatchReference.Substring(0, 16) + "..")</h4>
                        </div>
                        <div class="col-2 w232">
                            <h4> @batch.TotalNumberOfClaims</h4>
                        </div>
                        <div class="col-2 w232">
                            <h4> @batch.UploadedBy  </h4>
                        </div>
                        <div class="col-3 w183">
                            <h4>@batch.UploadedDate.ToString("dd/MM/yyyy HH:mm:ss")</h4>
                        </div>
                        <div class="col-3">
                            <h4>@batch.BatchStatusAsString</h4>
                        </div>
                        @*  <div class="col-7 paddingright_150"> *@



                        <div class="col-7 paddingleft_24" id="btnActions" >
                            @if (batch.BatchStatusAsString != "Loaded" && batch.BatchStatusAsString != "Rejected" && batch.BatchStatusAsString != "Error" && batch.BatchStatusAsString != "Complete")
                            {
                                <i data-field="action_event-@RowNum" id="actions-@RowNum" class="icon-small action-arrow marginleft_80" disabled> </i>
                            }
                            else
                            {
                                <i data-field="action_event-@RowNum" id="actions-@RowNum" class="icon-small action-arrow marginleft_80"> </i>
                            }

                            <div id="action_event-@RowNum" class="dropdownlist action_event_wide marginleft_811 wide_dropdowncontainer border-radius white_bg w186 right display_none">


                                @* <div id="action_event-@RowNum" class="dropdownlist actions   marginleft_801 action_dropdowncontainer border-radius white_bg w186 right display_none">*@

                                <div class="action_event_strip"></div>
                                @if (batch.BatchStatusAsString != "Rejected")
                                {
                                    <div class="left"><a href="#"> <i class="icon-large viewbatch left"></i> <strong class="alignleft margintop_5 GetBatchReport" style="text-align: left;" id="@batch.BatchId" name="@batch.ClientBatchReference">View Batch Report</strong> </a></div>
                                }
                                <div class="left"><a href="#"> <i class="icon-large viewbatch left"></i> <strong class="alignleft margintop_5 GetBatchProcessingResults" style="text-align:left;" id="@batch.BatchId">View Processing Results</strong> </a></div>
                            </div>
                        </div>

                    </div>
                            <!--row-2 div ends here-->

                }

            </div>

            <div id="PagingLinks" class="page_navigation marginleft_570 left">
                <!--proceedings_navigation div starts here-->
                <div class="left"> <a href="#" class="pageprev" id="prevNavLink" ><i class="icon-small prev_arrow" id="pageprevPointer" ></i></a> </div>


                <div class="text left">
                    <p>
                        @Model.PagingInfo.ItemStart - @Model.PagingInfo.ItemEnd of @Model.PagingInfo.TotalItems 
                    </p>
                </div>

                <div class="left"> <a href="#" class="pagenext" id="nextNavLink"><i class="icon-small next_arrow" id="pagenextPointer"></i></a> </div>
            </div>
            <!--proceedings_navigation div ends here-->
        </div>

    </div>
    <!--span18 div ends here-->
    <!--row div ends here-->
</div>



 @{Html.RenderPartial("_UIDialog");}

Ada.Service/KeoghsClientSite/Views/Upload/_UploadMenu.cshtml
@using KeoghsClientSite.StaticClasses

 <div class="clear"></div>
      <div class="row"> <!--row div starts here-->
    
    <div class="span6 border-radius tab_navigation   suffix_6"> <!--span4 div starts here-->
          
          <div class="headings w396 border_bottom left margintop_5">
                <div class="col-1 w252">
                      <h1>SINGLE CLAIM INPUT/h1>
                </div>
          </div>

          <br style="clear:both;"/>

               <div>
                @*  <div class="col-1">&nbsp; </div>
                  <div class="col-1"> <i class="icon-x-large under-construction"></i> </div>
                  <div class="col-1">UNDER CONSTRUCTION</div>*@
                      
                      <table border="0" width="100%">
                          <tr>
                              <td colspan="3">&nbsp;</td>
                          </tr>
                          <tr>
                              <td>&nbsp;</td><td align="center"> <i class="icon-x-large under-construction"></i></td><td>&nbsp;</td>
                          </tr>
                          <tr>
                              <td colspan="3" style="text-align:center;">UNDER CONSTRUCTION</td>
                          </tr>
                      </table>
                </div>

          @*<div class="singleclaim_container">
            <div class="col-1 w396"> <i class="icon-xx-large claiminput"></i> </div>
          </div>*@

    </div>
    <!--span6 div ends here-->
    
    <div class="span6 border-radius tab_navigation @Url.SetActiveUploadMenu("Upload","Index") prefix_6"> <!--span4 div starts here-->
          
        <a href="@Url.Content("~/Upload/Index")">
          <div class="headings w396  border_bottom_blue left  margintop_5">
                <div class="col-1 w252">
                  <h1 class="blue"></h1>
                </div>
          </div>
          <div class="singleclaim_container">
                <div class="col-1 w396"> <i class="icon-xx-large batchupload"></i> </div>
          </div>
            </a>
    </div>
    <!--span6 div ends here-->
    
    <div class="span6 border-radius tab_navigation @Url.SetActiveUploadMenu("Upload","OutstandingClaims") prefix_6"> <!--span4 div starts here-->

        <a href="@Url.Content("~/Upload/OutstandingClaims")">
          <div class="headings w396  border_bottom left  margintop_5">
                <div class="col-1 w252">
                  <h1>OUTSTANDING</h1>
                </div>
          </div>
          
          <div class="singleclaim_container">
                <div class="col-1 w396"> 
                    <i class="icon-xx-large claiminput left marginleft_50"></i> 
                    <strong class="left red"> 0 </strong> <b class="left"> Claims not <br>
                  yet submitted </b> 
                </div>
          </div>
            </a>

   </div>
    <!--span6 div ends here--> 
    
  </div>
      <!--row div ends here-->